//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplyChainManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryunit
    {
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<long> distributorid { get; set; }
        public string distributorname { get; set; }
        public Nullable<long> productid { get; set; }
        public string productname { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
