//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplyChainManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class scmEntities : DbContext
    {
        public scmEntities()
            : base("name=scmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<deliveryunit> deliveryunits { get; set; }
        public virtual DbSet<distributorunit> distributorunits { get; set; }
        public virtual DbSet<manufacturerunit> manufacturerunits { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<stakeholder> stakeholders { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
